<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
  /**
   * Run the database seeds.
   */
  public function run(): void
  {
    DB::table('users')->insert([
      [
        "name" =>  "Гориловский Лев Миронович",
        "name_short" =>  "Гориловский Л.М.",
        "position_id" =>  6,
        "department_id" =>  1,
        "birth_date" =>  Carbon::parse("04.09.1992"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  'delete@email.ru',
        "phone" =>  null,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Молчанов Владимир Владимирович",
        "name_short" =>  "Молчанов В.В.",
        "position_id" =>  24,
        "department_id" =>  2,
        "birth_date" =>  Carbon::parse("16.02.1983"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "mvv@matriks.group",
        "phone" =>  79610795245,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Камакшин Евгений Евгеньевич",
        "name_short" =>  "Камакшин Е.Е.",
        "position_id" =>  11,
        "department_id" =>  2,
        "birth_date" =>  Carbon::parse("29.03.1999"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "kee@matriks.group",
        "phone" =>  null,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Салямов Рустам Искендерович",
        "name_short" =>  "Салямов Р.И.",
        "position_id" =>  11,
        "department_id" =>  2,
        "birth_date" =>  Carbon::parse("10.03.1984"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "sri@matriks.group",
        "phone" =>  79965100216,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Котенко Ярослав Александрович",
        "name_short" =>  "Котенко Я.А.",
        "position_id" =>  10,
        "department_id" =>  2,
        "birth_date" =>  Carbon::parse("27.07.1990"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "kya@matriks.group",
        "phone" =>  null,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Евстигнеев Максим Александрович",
        "name_short" =>  "Евстигнеев М.А.",
        "position_id" =>  7,
        "department_id" =>  3,
        "birth_date" =>  Carbon::parse("02.12.1981"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "ema@matriks.group",
        "phone" =>  79214001575,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Яризов Станислав Евгеньевич",
        "name_short" =>  "Яризов С.Е.",
        "position_id" =>  8,
        "department_id" =>  3,
        "birth_date" =>  Carbon::parse("26.10.1972"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "yse@matriks.group",
        "phone" =>  79213048123,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Торчинский Алексей Эдуардович",
        "name_short" =>  "Торчинский А.Э.",
        "position_id" =>  30,
        "department_id" =>  3,
        "birth_date" =>  Carbon::parse("09.05.1974"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "tae@matriks.group",
        "phone" =>  79214001615,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Судалин Александр Игоревич",
        "name_short" =>  "Судалин А.И.",
        "position_id" =>  9,
        "department_id" =>  3,
        "birth_date" =>  Carbon::parse("23.10.1991"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "sudalin.a@matriks.group",
        "phone" =>  79241169933,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Акентьева Наталья Олеговна",
        "name_short" =>  "Акентьева Н.О.",
        "position_id" =>  34,
        "department_id" =>  4,
        "birth_date" =>  Carbon::parse("19.04.1957"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  'delete1@email.ru',
        "phone" =>  79602305849,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Кормилицына Александра Альбертовна",
        "name_short" =>  "Кормилицына А.А.",
        "position_id" =>  25,
        "department_id" =>  4,
        "birth_date" =>  Carbon::parse("25.12.1977"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "a.kormilicyna@matriks.group",
        "phone" =>  79111026302,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Васильев Алексей Игоревич",
        "name_short" =>  "Васильев А.И.",
        "position_id" =>  14,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("24.03.1999"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "a.vasilev@matriks.group ",
        "phone" =>  79817683813,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Вишневский Александр Владиленович",
        "name_short" =>  "Вишневский А.В.",
        "position_id" =>  14,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("04.11.1974"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "vav@matriks.group",
        "phone" =>  79119642737,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Потапов Павел Александрович",
        "name_short" =>  "Потапов П.А.",
        "position_id" =>  11,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("01.03.2000"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "potapov.p@matriks.group",
        "phone" =>  79118421073,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Русакова Алина Игоревна",
        "name_short" =>  "Русакова А.И.",
        "position_id" =>  14,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("19.10.1999"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "rusakova.a@matriks.group",
        "phone" =>  79939568571,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Семушин Матвей Васильевич",
        "name_short" =>  "Семушин М.В.",
        "position_id" =>  11,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("02.02.2003"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "smv@matriks.group",
        "phone" =>  79537529895,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Сидорова Таисия Викторовна",
        "name_short" =>  "Сидорова Т.В.",
        "position_id" =>  11,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("26.10.2001"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "sidorova.t@matriks.group",
        "phone" =>  79531675510,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Чапкий Илья Александрович",
        "name_short" =>  "Чапкий И.А.",
        "position_id" =>  11,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("24.11.2004"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "i.chapkiy@matriks.group",
        "phone" =>  79097873985,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Крайнова Елизавета Игоревна",
        "name_short" =>  "Крайнова Е.И.",
        "position_id" =>  3,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("09.06.1993"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "kei@matriks.group",
        "phone" =>  null,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Чуркин Вадим Александрович",
        "name_short" =>  "Чуркин В.А.",
        "position_id" =>  20,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("23.05.1971"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "v.churkin@matriks.group",
        "phone" =>  79112106838,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Минин Андрей Васильевич",
        "name_short" =>  "Минин А.В.",
        "position_id" =>  23,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("06.09.1982"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "mav@matriks.group",
        "phone" =>  79214152295,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Дворников Иван Валериевич",
        "name_short" =>  "Дворников И.В.",
        "position_id" =>  15,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("18.08.1988"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "i.dvornikov@matriks.group",
        "phone" =>  79218482364,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Ефимов Александр Дмитриевич",
        "name_short" =>  "Ефимов А.Д.",
        "position_id" =>  15,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("24.06.2001"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "ead@matriks.group",
        "phone" =>  null,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Иванов Александр Сергеевич",
        "name_short" =>  "Иванов А.С.",
        "position_id" =>  15,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("25.07.1999"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "ias@matriks.group",
        "phone" =>  null,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Калинин Максим Андреевич",
        "name_short" =>  "Калинин М.А.",
        "position_id" =>  15,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("14.07.2001"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "kma@matriks.group",
        "phone" =>  null,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Костянок Марсель Дмитриевич",
        "name_short" =>  "Костянок М.Д.",
        "position_id" =>  13,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("29.05.2002"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "m.kostyanok@matriks.group",
        "phone" =>  79819042264,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Мартынов Андрей Олегович",
        "name_short" =>  "Мартынов А.О.",
        "position_id" =>  12,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("06.10.1982"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "a.martynov@matriks.group",
        "phone" =>  79119231495,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Паутов Андрей Сергеевич",
        "name_short" =>  "Паутов А.С.",
        "position_id" =>  27,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("16.12.2001"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "a.pautov@matriks.group",
        "phone" =>  79111044910,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Ремизов Борис Константинович",
        "name_short" =>  "Ремизов Б.К.",
        "position_id" =>  27,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("12.11.1999"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "b.remizov@matriks.group",
        "phone" =>  79775987420,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Иванов Максим Олегович",
        "name_short" =>  "Иванов М.О.",
        "position_id" =>  26,
        "department_id" =>  5,
        "birth_date" =>  Carbon::parse("29.10.2005"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  'delete2@email.ru',
        "phone" =>  79522698035,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Гусев Андрей Владимирович",
        "name_short" =>  "Гусев А.В.",
        "position_id" =>  28,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("18.12.1968"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "a.gusev@matriks.group",
        "phone" =>  79030393671,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Сараев Константин Васильевич",
        "name_short" =>  "Сараев К.В.",
        "position_id" =>  15,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("25.08.1976"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  'delete3@email.ru',
        "phone" =>  null,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Федоров Илья Сергеевич",
        "name_short" =>  "Федоров И.С.",
        "position_id" =>  28,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("07.08.2001"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "fis@matriks.group",
        "phone" =>  79523048675,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Шевнин Евгений Алексеевич",
        "name_short" =>  "Шевнин Е.А.",
        "position_id" =>  28,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("30.07.1995"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "e.shevnin@matriks.group",
        "phone" =>  79127507680,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Петров Александр Юрьевич",
        "name_short" =>  "Петров А.Ю.",
        "position_id" =>  15,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("21.03.1997"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "petrov.a@matriks.group",
        "phone" =>  79118131772,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Фёдорова Анастасия Анатольевна",
        "name_short" =>  "Фёдорова А.А.",
        "position_id" =>  29,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("02.01.1998"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "faa@osmocode.ru",
        "phone" =>  79811888295,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Кузьмичев Дмитрий Александрович",
        "name_short" =>  "Кузьмичев Д.А.",
        "position_id" =>  21,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("08.09.2002"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "kuzmichev.d@matriks.group",
        "phone" =>  79217275931,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Морев Иван Олегович",
        "name_short" =>  "Морев И.О.",
        "position_id" =>  21,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("02.05.2002"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "morev.i@matriks.group",
        "phone" =>  79216538202,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Чуркин Никита Алексеевич",
        "name_short" =>  "Чуркин Н.А.",
        "position_id" =>  21,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("22.05.2002"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "churkin.n@matriks.group",
        "phone" =>  79967999485,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Чепелев Владимир Петрович",
        "name_short" =>  "Чепелев В.П.",
        "position_id" =>  31,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("15.04.1995"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "chvp@matriks.group",
        "phone" =>  79818280508,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Леонов Денис Александрович",
        "name_short" =>  "Леонов Д.А.",
        "position_id" =>  4,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("19.11.1976"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "d.leonov@matriks.group",
        "phone" =>  79522867914,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Судоргин Иван Владимирович",
        "name_short" =>  "Судоргин И.В.",
        "position_id" =>  5,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("29.04.1995"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "sudorgin.i@matriks.group",
        "phone" =>  79323000093,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Аникиев Валерий Вячеславович",
        "name_short" =>  "Аникиев В.В.",
        "position_id" =>  32,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("11.06.1966"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  'delete4@email.ru',
        "phone" =>  79602588999,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Казаков Илья Валентинович",
        "name_short" =>  "Казаков И.В.",
        "position_id" =>  32,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("06.04.1972"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  'delete5@email.ru',
        "phone" =>  79052650023,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Кашин Сергей Владимирович",
        "name_short" =>  "Кашин С.В.",
        "position_id" =>  32,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("23.10.1987"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  'delete6@email.ru',
        "phone" =>  79111758547,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Михайлов Никита Дмитриевич",
        "name_short" =>  "Михайлов Н.Д.",
        "position_id" =>  32,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("28.05.2004"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  'delete7@email.ru',
        "phone" =>  79523645867,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Дугин Алексей Сергеевич",
        "name_short" =>  "Дугин А.С.",
        "position_id" =>  22,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("07.03.1997"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  'delete8@email.ru',
        "phone" =>  79819800070,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Новоселов Дмитрий Сергеевич",
        "name_short" =>  "Новоселов Д.С.",
        "position_id" =>  19,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("20.04.1988"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "d.novoselov@matriks.group",
        "phone" =>  79215659262,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Колмогорова Екатерина Геннадьевна",
        "name_short" =>  "Колмогорова Е.Г.",
        "position_id" =>  33,
        "department_id" =>  6,
        "birth_date" =>  Carbon::parse("22.05.1990"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "e.kolmogorova@matriks.group",
        "phone" =>  79319540296,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Ахтямов Марат Рауфович",
        "name_short" =>  "Ахтямов М.Р.",
        "position_id" =>  2,
        "department_id" =>  7,
        "birth_date" =>  Carbon::parse("14.04.1985"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "amr@matriks.group",
        "phone" =>  79218836285,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Розензафт Тамара Марковна",
        "name_short" =>  "Розензафт Т.М.",
        "position_id" =>  34,
        "department_id" =>  7,
        "birth_date" =>  Carbon::parse("27.12.1976"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "rtm@matriks.group",
        "phone" =>  79315863510,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Смирнова Елена Денисовна",
        "name_short" =>  "Смирнова Е.Д.",
        "position_id" =>  1,
        "department_id" =>  7,
        "birth_date" =>  Carbon::parse("10.10.2001"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "smirnova.e@matriks.group",
        "phone" =>  79516704295,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Арасланова Алсу",
        "name_short" =>  "Арасланова А.",
        "position_id" =>  34,
        "department_id" =>  8,
        "birth_date" =>  Carbon::parse("16.09.1980"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "araslanova.a@matriks.group",
        "phone" =>  79213173117,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Дерюшева Лариса",
        "name_short" =>  "Дерюшева Л.",
        "position_id" =>  34,
        "department_id" =>  8,
        "birth_date" =>  Carbon::parse("18.12.1968"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "dlg@matriks.group",
        "phone" =>  79219644730,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Калитин Александр",
        "name_short" =>  "Калитин А.",
        "position_id" =>  34,
        "department_id" =>  8,
        "birth_date" =>  Carbon::parse("05.09.1998"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "kao@matriks.group",
        "phone" =>  null,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Надеждин Кирилл",
        "name_short" =>  "Надеждин К.",
        "position_id" =>  29,
        "department_id" =>  8,
        "birth_date" =>  Carbon::parse("09.03.2000"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "nka@matriks.group",
        "phone" =>  null,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Олехнович Александр",
        "name_short" =>  "Олехнович А.",
        "position_id" =>  2,
        "department_id" =>  8,
        "birth_date" =>  Carbon::parse("10.03.1982"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "oag@matriks.group",
        "phone" =>  79215727390,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Сучок Василий",
        "name_short" =>  "Сучок В.",
        "position_id" =>  2,
        "department_id" =>  8,
        "birth_date" =>  Carbon::parse("19.09.1997"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "svv@matriks.group",
        "phone" =>  79213824906,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Сычев Андрей",
        "name_short" =>  "Сычев А.",
        "position_id" =>  40,
        "department_id" =>  8,
        "birth_date" =>  Carbon::parse("07.02.1979"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "san@matriks.group",
        "phone" =>  79118321669,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Петрова Анастасия",
        "name_short" =>  "Петрова А.",
        "position_id" =>  40,
        "department_id" =>  8,
        "birth_date" =>  Carbon::parse("03.04.1995"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "a.petrova@matriks.group",
        "phone" =>  79215960315,
        "user_status_id" =>  1,
        "settings" => '[]'
      ],
      [
        "name" =>  "Федоров Виктор",
        "name_short" =>  "Федоров В.",
        "position_id" =>  10,
        "department_id" =>  8,
        "birth_date" =>  Carbon::parse("09.03.1996"),
        'password' => hash::make('12345678'),
        'user_role_id' => 1,
        "email" =>  "fedorov@matriks.group",
        "phone" =>  79311029388,
        "user_status_id" =>  1,
        "settings" => '[]'
      ]
    ]);
  }
}
